Training notebook

In [1]:
import pandas as pd

In [ ]:
df=pd.read_csv('dataset/synthetic_logs.csv')

df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert
...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert

In [7]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [8]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [33]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
import numpy as np

#load pre trained sentence transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

#generate embeddings for the logs
embeddings = model.encode(df['log_message'].tolist())

#perform DBSCAN Clustering
dbscan= DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters=dbscan.fit_predict(embeddings)

#add cluster labels to the dataframe
df['cluster']=clusters

#visualize the clusters
df['cluster']

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

0       0
1       1
2       2
3       0
4       0
       ..
2405    0
2406    7
2407    0
2408    1
2409    7
Name: cluster, Length: 2410, dtype: int64

In [37]:
df['cluster'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135])

In [36]:
df[df['cluster'] == 5]['log_message'].head()

8     nova.compute.claims [req-a07ac654-8e81-416d-bf...
26    nova.compute.claims [req-d6986b54-3735-4a42-90...
40    nova.compute.claims [req-72b4858f-049e-49e1-b3...
58    nova.compute.claims [req-5c8f52bd-8e3c-41f0-95...
61    nova.compute.claims [req-d38f479d-9bb9-4276-96...
Name: log_message, dtype: object

In [40]:
df[df.cluster==7]

,timestamp,source,log_message,target_label,complexity,cluster
13,8/4/2025 19:57,ThirdPartyAPI,Multiple bad login attempts detected on user 8...,Security Alert,bert,7
53,7/29/2025 0:17,ModernHR,Multiple login failures occurred on user 9052 ...,Security Alert,bert,7
72,2/3/2025 5:35,AnalyticsEngine,User 7153 made multiple incorrect login attempts,Security Alert,bert,7
74,5/9/2025 21:18,BillingSystem,User 8300 made multiple incorrect login attempts,Security Alert,bert,7
113,9/3/2025 2:46,ThirdPartyAPI,Multiple login failures were detected for user...,Security Alert,bert,7
130,12/21/2025 19:36,ThirdPartyAPI,Multiple failed login attempts were reported f...,Security Alert,bert,7
168,5/19/2025 7:56,ModernHR,Multiple incorrect login attempts were made by...,Security Alert,bert,7
173,11/30/2025 2:29,AnalyticsEngine,User 9167 experienced repeated login failures,Security Alert,bert,7
295,8/18/2025 6:57,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7
318,12/28/2025 2:39,AnalyticsEngine,User 9131 made multiple failed login attempts,Security Alert,bert,7
356,8/18/2025 8:06,ModernHR,User 8075 made multiple failed login attempts,Security Alert,bert,7
423,12/24/2025 19:51,ModernCRM,User 8276 account experienced multiple login f...,Security Alert,bert,7
452,1/20/2025 5:35,ModernCRM,User 5456 experienced multiple login rejections,Security Alert,bert,7
503,4/24/2025 2:57,ModernHR,User 7790 account had multiple failed login tries,Security Alert,bert,7
511,12/28/2025 12:17,ModernCRM,Multiple invalid login attempts were made for ...,Security Alert,bert,7
631,12/29/2025 10:27,ThirdPartyAPI,User 1403 had multiple login attempts rejected,Security Alert,bert,7
698,3/14/2025 10:55,BillingSystem,User 3330 account experienced multiple login f...,Security Alert,bert,7
847,11/19/2025 13:14,BillingSystem,Repeated failed login attempts occurred for us...,Security Alert,bert,7
900,8/5/2025 15:12,BillingSystem,Multiple invalid login attempts were made for ...,Security Alert,bert,7
945,3/5/2025 21:50,ThirdPartyAPI,User 1884 experienced repeated login failures,Security Alert,bert,7
1109,9/18/2025 21:20,ModernHR,User 7937 had multiple login attempts rejected,Security Alert,bert,7
1132,4/14/2025 9:07,AnalyticsEngine,Several login attempts by user 8161 were unsuc...,Security Alert,bert,7
1137,7/8/2025 13:20,BillingSystem,User 2957 account had multiple failed login tries,Security Alert,bert,7
1212,9/8/2025 2:52,ModernHR,User 2104 made multiple failed login attempts,Security Alert,bert,7
1220,11/17/2025 3:49,ModernCRM,Multiple login failures occurred on user 7102 ...,Security Alert,bert,7
1225,8/3/2025 7:51,BillingSystem,User 5555 account experienced multiple login f...,Security Alert,bert,7
1284,7/16/2025 4:47,ThirdPartyAPI,Multiple rejected login attempts found for use...,Security Alert,bert,7
1301,2/11/2025 11:10,ModernHR,User 3424 experienced multiple login rejections,Security Alert,bert,7
1356,5/3/2025 13:03,ThirdPartyAPI,Multiple rejected login attempts found for use...,Security Alert,bert,7
1378,5/2/2025 2:59,ThirdPartyAPI,Multiple incorrect login attempts were made by...,Security Alert,bert,7
1384,11/28/2025 0:35,ThirdPartyAPI,User 2344 had multiple unsuccessful login atte...,Security Alert,bert,7
1398,9/24/2025 6:50,AnalyticsEngine,Multiple login failures occurred on user 6454 ...,Security Alert,bert,7
1421,9/28/2025 21:51,ModernCRM,User 5045 had multiple unsuccessful login atte...,Security Alert,bert,7
1487,11/10/2025 18:36,BillingSystem,User 5019 had multiple unsuccessful login atte...,Security Alert,bert,7
1525,10/26/2025 7:10,ThirdPartyAPI,Multiple login failures were detected for user...,Security Alert,bert,7
1545,10/19/2025 0:00,BillingSystem,Several unsuccessful login tries found for use...,Security Alert,bert,7
1627,4/16/2025 7:04,AnalyticsEngine,Multiple login failures were detected for user...,Security Alert,bert,7
1667,4/3/2025 14:00,AnalyticsEngine,Multiple rejected login attempts found for use...,Security Alert,bert,7
1693,3/4/2025 11:49,AnalyticsEngine,Multiple failed login attempts were reported f...,Security Alert,bert,7
1711,8/18/2025 16:13,ModernHR,Several login attempts by user 6641 were unsuc...,Security Alert,bert,7
1745,3/4/2025 3:41,ThirdPartyAPI,Several unsuccessful login tries found for use...,Security Alert,bert,7
1768,12/20/2025 5:19,ModernHR,Multiple failed login tries occurred for user ...,Security Alert,bert,7
1781,2/25/2025 22:06,ThirdPartyAPI,User 4288 made multiple incorrect login attempts,Security Alert,bert,7
1866,6/29/2025 10:37,ThirdPartyAPI,User 3692 account had multiple failed login tries,Security Alert,bert,7
1890,3/27/2025 7:44,BillingSystem,Multiple failed login attempts were reported f...,Security Alert,bert,7
1932,6/27/2025 2:39,BillingSystem,User 2750 had multiple login attempts rejected,Security Alert,bert,7
1947,8/8/2025 15:03,ModernHR,Multiple failed login tries occurred for user ...,Security Alert,bert,7
1975,4/21/2025 18:15,ThirdPartyAPI,User 4489 experienced repeated login failures,Security Alert,bert,7
2085,12/23/2025 13:44,ModernHR,Multiple failed login tries occurred for user ...,Security Alert,bert,7
2103,8/17/2025 3:05,ModernCRM,Multiple invalid login attempts were made for ...,Security Alert,bert,7
2117,1/26/2025 15:27,ModernCRM,Multiple incorrect login attempts were made by...,Security Alert,bert,7
2155,6/1/2025 4:37,BillingSystem,User 8382 account experienced multiple failed ...,Security Alert,bert,7
2250,1/17/2025 10:35,ModernCRM,Multiple bad login attempts detected on user 8...,Security Alert,bert,7
2274,5/18/2025 12:36,ModernCRM,Several login attempts by user 8694 were unsuc...,Security Alert,bert,7
2283,2/18/2025 23:13,ModernCRM,Several unsuccessful login tries found for use...,Security Alert,bert,7
2308,11/1/2025 21:38,ModernCRM,User 8048 account experienced multiple failed ...,Security Alert,bert,7
2324,9/22/2025 17:28,ThirdPartyAPI,User 1587 experienced multiple login rejections,Security Alert,bert,7
2343,11/14/2025 11:41,ModernHR,Multiple bad login attempts detected on user 4...,Security Alert,bert,7
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7

In [45]:
#sort clusters by number of records in it. print 5 logs that belong to each cluster.
df.groupby('cluster').size().sort_values(ascending=False)

cluster
0      1017
5       147
11      100
13       86
7        60
       ...
102       1
103       1
105       1
106       1
135       1
Length: 136, dtype: int64